name: "Lint"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
    contents: read

jobs:
    ruff-format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Set up Python 3.12
              uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
              with:
                  python-version: "3.12"
                  cache: "pip"
    
            - name: "Install requirements"
              run: python3 -m pip install -r requirements.txt

            - name: Run ruff format
              run: |
                ruff format --diff --target-version=py312 .

    ruff:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Set up Python 3.12
              uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
              with:
                  python-version: "3.12"
                  cache: "pip"

            - name: "Install requirements"
              run: python3 -m pip install -r requirements.txt
            
            - name: Run ruff
              run: |
                ruff check --output-format=github .
